name: IrSO Functional Tests

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  test:
    runs-on: ubuntu-latest-4-cores
    env:
      CLUSTER_TYPE: minikube
      LOGDIR: /tmp/logs
      JUNIT_OUTPUT: /tmp/logs/report.xml
    steps:
    - name: Update repositories
      run: sudo apt-get update
    - name: Install podman
      run: sudo apt-get install -y podman
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        path: ironic-image
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: metal3-io/ironic-standalone-operator
        path: ironic-standalone-operator
    - name: Calculate go version
      id: vars
      run: echo "go_version=$(make -sC ironic-standalone-operator go-version)" >> $GITHUB_OUTPUT
    - name: Set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: ${{ steps.vars.outputs.go_version }}
    - name: Setup a minikube cluster
      uses: medyagh/setup-minikube@e3c7f79eb1e997eabccc536a6cf318a2b0fe19d9 # v0.0.20
      with:
        start-args: "--ha"
    - name: Prepare tests
      run: cd ironic-standalone-operator && ./test/prepare.sh
    - name: Run tests
      run: ironic-image/hack/ci-e2e.sh
      env:
        IRSO_PATH: "${{ github.workspace }}/ironic-standalone-operator"
    - name: Collect logs
      run: ironic-standalone-operator/test/collect-logs.sh
      if: always()
    - name: Upload logs artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: functional
        path: /tmp/logs/*
      if: always()
    - name: Annotate failures
      uses: mikepenz/action-junit-report@3585e9575db828022551b4231f165eb59a0e74e3 # v5.6.2
      with:
        annotate_only: true
        report_paths: /tmp/logs/report.xml
      if: always()
