name: IrSO Functional Tests

on:
  pull_request:
    types: [ opened, edited, reopened, synchronize, ready_for_review ]

jobs:
  test:
    runs-on: oracle-vm-4cpu-16gb-x86-64
    env:
      CLUSTER_TYPE: minikube
      CONTAINER_RUNTIME: docker
      LOGDIR: /tmp/logs
      JUNIT_OUTPUT: /tmp/logs/report.xml
      IRONIC_CUSTOM_IMAGE: localhost/ironic:test
      # NOTE(dtantsur): change this on stable branches to make sure the correct
      # logic is used in IrSO, and also that the tests are skipped properly.
      IRONIC_CUSTOM_VERSION: "34.0"
    steps:
    - name: Check docker version
      run: docker --version
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      with:
        path: ironic-image
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      with:
        repository: metal3-io/ironic-standalone-operator
        path: ironic-standalone-operator
    - name: Calculate go version
      id: vars
      run: echo "go_version=$(make -sC ironic-standalone-operator go-version)" >> $GITHUB_OUTPUT
    - name: Set up Go
      uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
      with:
        go-version: ${{ steps.vars.outputs.go_version }}
    - name: Setup a minikube cluster
      uses: medyagh/setup-minikube@e9e035a86bbc3caea26a450bd4dbf9d0c453682e # v0.0.21
      with:
        start-args: "--ha"
    - name: Prepare tests
      run: ironic-standalone-operator/test/prepare.sh
    - name: Build and local the image
      run: ironic-image/hack/prepare-irso-tests.sh
    - name: Run tests
      run: ironic-standalone-operator/test/run.sh
    - name: Collect logs
      run: ironic-standalone-operator/test/collect-logs.sh
      if: always()
    - name: Upload logs artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: functional
        path: /tmp/logs/*
      if: always()
    - name: Annotate failures
      uses: mikepenz/action-junit-report@3585e9575db828022551b4231f165eb59a0e74e3 # v5.6.2
      with:
        annotate_only: true
        report_paths: /tmp/logs/report.xml
      if: always()
