name: IrSO Functional Tests

on:
  pull_request:
    types: [ opened, edited, reopened, synchronize, ready_for_review ]

jobs:
  test:
    runs-on: oracle-vm-4cpu-16gb-x86-64
    env:
      CLUSTER_TYPE: minikube
      CONTAINER_RUNTIME: docker
      LOGDIR: /tmp/logs
      JUNIT_OUTPUT: /tmp/logs/report.xml
      IRONIC_CUSTOM_IMAGE: localhost/ironic:test
      # NOTE(dtantsur): change this on stable branches to make sure the correct
      # logic is used in IrSO, and also that the tests are skipped properly.
      IRONIC_CUSTOM_VERSION: latest
    steps:
    - name: Check docker version
      run: docker --version
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        path: ironic-image
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        repository: metal3-io/ironic-standalone-operator
        path: ironic-standalone-operator
    - name: Calculate go version
      id: vars
      run: echo "go_version=$(make -sC ironic-standalone-operator go-version)" >> $GITHUB_OUTPUT
    - name: Set up Go
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
      with:
        go-version: ${{ steps.vars.outputs.go_version }}
    - name: Setup a minikube cluster
      uses: medyagh/setup-minikube@e9e035a86bbc3caea26a450bd4dbf9d0c453682e # v0.0.21
      with:
        start-args: "--ha"
    - name: Prepare tests
      run: ironic-standalone-operator/test/prepare.sh
    - name: Build and local the image
      run: ironic-image/hack/prepare-irso-tests.sh
    - name: Run tests
      run: ironic-standalone-operator/test/run.sh
    - name: Collect logs
      run: ironic-standalone-operator/test/collect-logs.sh
      if: always()
    - name: Upload logs artifacts
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: functional
        path: /tmp/logs/*
      if: always()
    - name: Annotate failures
      uses: mikepenz/action-junit-report@5e05ac00ad0604dfb7e313ae412aa3284f4906d6 # v6.3.0
      with:
        annotate_only: true
        report_paths: /tmp/logs/report.xml
      if: always()
